/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TYPES_H_RPCGEN
#define _TYPES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef quad_t xdrhyper;

typedef struct {
	u_int xdrhypersequence_len;
	quad_t *xdrhypersequence_val;
} xdrhypersequence;

struct Response {
	xdrhypersequence request;
	xdrhypersequence response;
};
typedef struct Response Response;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_xdrhyper (XDR *, xdrhyper*);
extern  bool_t xdr_xdrhypersequence (XDR *, xdrhypersequence*);
extern  bool_t xdr_Response (XDR *, Response*);

#else /* K&R C */
extern bool_t xdr_xdrhyper ();
extern bool_t xdr_xdrhypersequence ();
extern bool_t xdr_Response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TYPES_H_RPCGEN */
